// Mocks generated by Mockito 5.4.6 from annotations
// in servi_pro/test/feature/application/application_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:servi_pro/core/errors/failures.dart' as _i5;
import 'package:servi_pro/features/application/domain/entities/application_entity.dart'
    as _i7;
import 'package:servi_pro/features/application/domain/repositories/application_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApplicationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplicationRepository extends _i1.Mock
    implements _i2.ApplicationRepository {
  MockApplicationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> addAplication({
    required String? idWorker,
    required String? idRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAplication, [], {
              #idWorker: idWorker,
              #idRequest: idRequest,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#addAplication, [], {
                  #idWorker: idWorker,
                  #idRequest: idRequest,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i7.ApplicationEntity>>>
  getAppliForRequest({required String? idRequest}) =>
      (super.noSuchMethod(
            Invocation.method(#getAppliForRequest, [], {#idRequest: idRequest}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i7.ApplicationEntity>>
                >.value(
                  _i6.dummyValue<
                    _i4.Either<_i5.Failure, List<_i7.ApplicationEntity>>
                  >(
                    this,
                    Invocation.method(#getAppliForRequest, [], {
                      #idRequest: idRequest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i7.ApplicationEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i7.ApplicationEntity>>>
  getAppliForWorker({required String? idWorker}) =>
      (super.noSuchMethod(
            Invocation.method(#getAppliForWorker, [], {#idWorker: idWorker}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i7.ApplicationEntity>>
                >.value(
                  _i6.dummyValue<
                    _i4.Either<_i5.Failure, List<_i7.ApplicationEntity>>
                  >(
                    this,
                    Invocation.method(#getAppliForWorker, [], {
                      #idWorker: idWorker,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i7.ApplicationEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> cancelApplication({
    required String? id,
    required String? idRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelApplication, [], {
              #id: id,
              #idRequest: idRequest,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#cancelApplication, [], {
                  #id: id,
                  #idRequest: idRequest,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> acceptApplication({
    required String? applicationId,
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptApplication, [], {
              #applicationId: applicationId,
              #requestId: requestId,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#acceptApplication, [], {
                  #applicationId: applicationId,
                  #requestId: requestId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> completeRequest({
    required String? applicationId,
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeRequest, [], {
              #applicationId: applicationId,
              #requestId: requestId,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#completeRequest, [], {
                  #applicationId: applicationId,
                  #requestId: requestId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}
