// Mocks generated by Mockito 5.4.6 from annotations
// in servi_pro/test/feature/request/request_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:servi_pro/core/errors/failures.dart' as _i5;
import 'package:servi_pro/features/requests/domain/entities/request_entity.dart'
    as _i6;
import 'package:servi_pro/features/requests/domain/repository/request_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RequestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestRepository extends _i1.Mock implements _i2.RequestRepository {
  MockRequestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> registerRequest(
    _i6.RequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerRequest, [request]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#registerRequest, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.RequestEntity>>> allRequest() =>
      (super.noSuchMethod(
            Invocation.method(#allRequest, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i6.RequestEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i6.RequestEntity>>
                  >(this, Invocation.method(#allRequest, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.RequestEntity>>>);

  @override
  _i3.Stream<List<_i6.RequestEntity>> watchAllRequests() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllRequests, []),
            returnValue: _i3.Stream<List<_i6.RequestEntity>>.empty(),
          )
          as _i3.Stream<List<_i6.RequestEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> deleteRequest(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRequest, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#deleteRequest, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.RequestEntity>> getRequestById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRequestById, [id]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.RequestEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.RequestEntity>>(
                    this,
                    Invocation.method(#getRequestById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.RequestEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> markAsCompleted({
    required String? requestId,
    required String? workerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAsCompleted, [], {
              #requestId: requestId,
              #workerId: workerId,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#markAsCompleted, [], {
                  #requestId: requestId,
                  #workerId: workerId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> confirmCompletion({
    required String? requestId,
    required String? clientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmCompletion, [], {
              #requestId: requestId,
              #clientId: clientId,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#confirmCompletion, [], {
                  #requestId: requestId,
                  #clientId: clientId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}
