// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKGnCOER28RYCaG_XRDbSOv8sFWiP87tA',
    appId: '1:283567111668:web:6742875ed70b798e7f8da1',
    messagingSenderId: '283567111668',
    projectId: 'servipro-46fad',
    authDomain: 'servipro-46fad.firebaseapp.com',
    storageBucket: 'servipro-46fad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPqUm_xuO8BaH2aRt40OSUY3nICthEGo',
    appId: '1:283567111668:android:f89bcff03b6f27687f8da1',
    messagingSenderId: '283567111668',
    projectId: 'servipro-46fad',
    storageBucket: 'servipro-46fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgxUcViLmVwb3TzNO5y-Z_8YlDOVyT5LI',
    appId: '1:283567111668:ios:1da5ba0e9d816a497f8da1',
    messagingSenderId: '283567111668',
    projectId: 'servipro-46fad',
    storageBucket: 'servipro-46fad.firebasestorage.app',
    iosBundleId: 'com.example.serviPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgxUcViLmVwb3TzNO5y-Z_8YlDOVyT5LI',
    appId: '1:283567111668:ios:1da5ba0e9d816a497f8da1',
    messagingSenderId: '283567111668',
    projectId: 'servipro-46fad',
    storageBucket: 'servipro-46fad.firebasestorage.app',
    iosBundleId: 'com.example.serviPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKGnCOER28RYCaG_XRDbSOv8sFWiP87tA',
    appId: '1:283567111668:web:9d04da31b08eb07c7f8da1',
    messagingSenderId: '283567111668',
    projectId: 'servipro-46fad',
    authDomain: 'servipro-46fad.firebaseapp.com',
    storageBucket: 'servipro-46fad.firebasestorage.app',
  );

}