// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdgsCy_OzV8TzHsLCwWApykSypUBP8_k4',
    appId: '1:24631487108:web:5297d247326e9d0f6370d1',
    messagingSenderId: '24631487108',
    projectId: 'servipro-3589c',
    authDomain: 'servipro-3589c.firebaseapp.com',
    storageBucket: 'servipro-3589c.firebasestorage.app',
    measurementId: 'G-H3227J639P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Ngf8If0zQqofj8jHfIrpfax7pDEkf6g',
    appId: '1:24631487108:android:a8bbb56ee05d874e6370d1',
    messagingSenderId: '24631487108',
    projectId: 'servipro-3589c',
    storageBucket: 'servipro-3589c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC32zwGfwPCQ2c52eQwhWjgTN6md7KMcPQ',
    appId: '1:24631487108:ios:ff974f641be680696370d1',
    messagingSenderId: '24631487108',
    projectId: 'servipro-3589c',
    storageBucket: 'servipro-3589c.firebasestorage.app',
    iosBundleId: 'com.example.serviPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC32zwGfwPCQ2c52eQwhWjgTN6md7KMcPQ',
    appId: '1:24631487108:ios:ff974f641be680696370d1',
    messagingSenderId: '24631487108',
    projectId: 'servipro-3589c',
    storageBucket: 'servipro-3589c.firebasestorage.app',
    iosBundleId: 'com.example.serviPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdgsCy_OzV8TzHsLCwWApykSypUBP8_k4',
    appId: '1:24631487108:web:5d2b7efe5903070b6370d1',
    messagingSenderId: '24631487108',
    projectId: 'servipro-3589c',
    authDomain: 'servipro-3589c.firebaseapp.com',
    storageBucket: 'servipro-3589c.firebasestorage.app',
    measurementId: 'G-ZW58E9J04H',
  );

}